name: Monitor Agent - Weekly Health Check

on:
  schedule:
    # Run every Monday at 02:00 UTC
    - cron: '0 2 * * 1'
  workflow_dispatch:
    # Allow manual triggering for testing

jobs:
  monitor:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Run monitor agent
      env:
        DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
        NODE_ENV: production
      run: |
        echo "🚀 Starting monitor agent execution..."
        tsx scripts/monitor-agent.ts
        echo "✅ Monitor agent completed successfully"
        
    - name: Upload logs on failure
      if: failure()
      uses: actions/upload-artifact@v4
      with:
        name: monitor-logs-${{ github.run_id }}
        path: |
          logs/
          data/
        retention-days: 7
        
    - name: Notify on failure
      if: failure()
      run: |
        echo "❌ Monitor agent failed - check logs for details"
        echo "Run ID: ${{ github.run_id }}"
        echo "Commit: ${{ github.sha }}"